In [1]:
# environment_classifier_train.py

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import joblib

# 1. Load dataset
df = pd.read_csv("/content/environment_dataset.csv")  # Make sure this file is in the same directory

# 2. Encode class labels to integers
label_encoder = LabelEncoder()
df['label_encoded'] = label_encoder.fit_transform(df['label'])

# 3. Define features and target
features = ["temperature", "humidity", "mq135_ao", "ldr_ao", "soil_ao"]
X = df[features]
y = df["label_encoded"]

# 4. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 5. Train the model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 6. Evaluate
y_pred = model.predict(X_test)
print("Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("Confusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

# 7. Save the model and encoder
joblib.dump(model, "environment_model.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")
print("\n✅ Model and encoder saved successfully!")


Classification Report:

                  precision    recall  f1-score   support

       Low Light       1.00      1.00      1.00       120
         Optimal       1.00      1.00      1.00       120
Poor Air Quality       1.00      1.00      1.00       120
     Too Hot/Dry       1.00      1.00      1.00       120
         Too Wet       1.00      1.00      1.00       120
     Unfavorable       1.00      1.00      1.00       120

        accuracy                           1.00       720
       macro avg       1.00      1.00      1.00       720
    weighted avg       1.00      1.00      1.00       720

Confusion Matrix:

[[120   0   0   0   0   0]
 [  0 120   0   0   0   0]
 [  0   0 120   0   0   0]
 [  0   0   0 120   0   0]
 [  0   0   0   0 120   0]
 [  0   0   0   0   0 120]]

✅ Model and encoder saved successfully!


In [8]:
import joblib
import numpy as np

# Load trained model and label encoder
model = joblib.load("environment_model.pkl")
label_encoder = joblib.load("label_encoder.pkl")

# 🔢 Example sensor input (real or simulated)
# Replace with actual values from your ESP32 readings
input_data = np.array([[30.80, 75.0, 1317, 3515, 4092]])  # Shape: (1, 5)

# Predict class
predicted_class_index = model.predict(input_data)[0]
predicted_class_label = label_encoder.inverse_transform([predicted_class_index])[0]

print("✅ Predicted Environment Class:", predicted_class_label)


✅ Predicted Environment Class: Too Hot/Dry


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
